### ISSUE TITLE
createCryptogram

### ISSUE THREAD

**Issue by Kenedi231** [gazaret/react-native-cloudpayments#6]
Привет, при создание криптограммы я получаю следущие ошибки ({"name": "RNCloudPaymentsError", "message": "unknown key type passed to RSA"} или  {"name":"RNCloudPaymentsError","message":"null is not an object (evaluating 'p.createCryptogram')"} ). Может будут идеи с чем это связано

**Comment by Kenedi231** [comment]
Привет, при создание криптограммы я получаю следущие ошибки ({"name": "RNCloudPaymentsError", "message": "unknown key type passed to RSA"} или {"name":"RNCloudPaymentsError","message":"null is not an object (evaluating 'p.createCryptogram')"} ). Может будут идеи с чем это связано

**Comment by alanses** [comment]
Hi, problem still exist, any update ?

**Comment by komdil** [comment]
Any updates??

**Comment by Kenedi231** [comment]
HI. I forked to myself and changed a couple of things. It works for me. Install:
`yarn add https://github.com/Kenedi231/react-native-cloudpayments.git`
I hope helped with something.

> Any updates??

**Comment by komdil** [comment]
> HI. I forked to myself and changed a couple of things. It works for me. Install:
> `yarn add https://github.com/Kenedi231/react-native-cloudpayments.git`
> I hope helped with something.
> 
> > Any updates??

I am getting RNCloudPaymentsError: Expiration date is not correct.

**Comment by Kenedi231** [comment]
> > HI. I forked to myself and changed a couple of things. It works for me. Install:
> > `yarn add https://github.com/Kenedi231/react-native-cloudpayments.git`
> > I hope helped with something.
> > > Any updates??
> 
> I am getting RNCloudPaymentsError: Expiration date is not correct.
> 
> I am using demoCard from example

In what form do you send extDate?

**Comment by komdil** [comment]
> > > HI. I forked to myself and changed a couple of things. It works for me. Install:
> > > `yarn add https://github.com/Kenedi231/react-native-cloudpayments.git`
> > > I hope helped with something.
> > > > Any updates??
> > 
> > 
> > I am getting RNCloudPaymentsError: Expiration date is not correct.
> > I am using demoCard from example
> 
> In what form do you send extDate?

In createCryptogram. When expDate 
is 10/18 it will throw Expiration date is not correct
is 10/20 (current year) it will throw Expiration date is not correct
is 1018 it will throw Expiration date is not correct
is 1020 it will work

My problem is solved but I am not sure is it correct or not. Maybe instead of Expiration date is not correct it will throw Card is expired in 1018 case?

**Comment by Kenedi231** [comment]
> > > > HI. I forked to myself and changed a couple of things. It works for me. Install:
> > > > `yarn add https://github.com/Kenedi231/react-native-cloudpayments.git`
> > > > I hope helped with something.
> > > > > Any updates??
> > > 
> > > 
> > > I am getting RNCloudPaymentsError: Expiration date is not correct.
> > > I am using demoCard from example
> > 
> > 
> > In what form do you send extDate?
> 
> In createCryptogram. When expDate
> is 10/18 it will throw Expiration date is not correct
> is 10/20 (current year) it will throw Expiration date is not correct
> is 1018 it will throw Expiration date is not correct
> is 1020 it will work
> 
> My problem is solved but I am not sure is it correct or not. Maybe instead of Expiration date is not correct it will throw Card is expired in 1018 case?

In this case, everything is correct. expDate cannot be less than the current date).

The only working case is 1020. You need to parse the string to the current view, and check that the date does not expire.
